version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    container_name: api-solid-pg
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    ports:
      - "5432:5432"
